// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyqqmgathdljtoidubmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cXFtZ2F0aGRsanRvaWR1Ym12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0ODY1MTksImV4cCI6MjA4ODA2MjUxOX0.7gRDBk_khXcyo5XMs3YMDPjT4OM8lMuIbdjZloRG5zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});